import { elements } from "./elements";

describe("Element Tag to Class Interface Store", () => {
  it("contents match expectations", () => {
    expect(elements).toMatchInlineSnapshot(`
      Object {
        "a": [Function],
        "area": [Function],
        "audio": [Function],
        "blockquote": [Function],
        "body": [Function],
        "br": [Function],
        "button": [Function],
        "canvas": [Function],
        "caption": [Function],
        "col": [Function],
        "colgroup": [Function],
        "data": [Function],
        "datalist": [Function],
        "del": [Function],
        "details": [Function],
        "div": [Function],
        "dl": [Function],
        "embed": [Function],
        "fieldset": [Function],
        "form": [Function],
        "h1": [Function],
        "h2": [Function],
        "h3": [Function],
        "h4": [Function],
        "h5": [Function],
        "h6": [Function],
        "head": [Function],
        "hr": [Function],
        "html": [Function],
        "iframe": [Function],
        "img": [Function],
        "input": [Function],
        "ins": [Function],
        "label": [Function],
        "legend": [Function],
        "li": [Function],
        "link": [Function],
        "map": [Function],
        "menu": [Function],
        "meta": [Function],
        "meter": [Function],
        "object": [Function],
        "ol": [Function],
        "optgroup": [Function],
        "option": [Function],
        "output": [Function],
        "p": [Function],
        "param": [Function],
        "picture": [Function],
        "pre": [Function],
        "progress": [Function],
        "q": [Function],
        "script": [Function],
        "select": [Function],
        "slot": [Function],
        "source": [Function],
        "span": [Function],
        "style": [Function],
        "table": [Function],
        "tbody": [Function],
        "td": [Function],
        "template": [Function],
        "textarea": [Function],
        "tfoot": [Function],
        "th": [Function],
        "thead": [Function],
        "time": [Function],
        "title": [Function],
        "tr": [Function],
        "track": [Function],
        "ul": [Function],
        "video": [Function],
      }
    `);
  });
});
